### ISSUE TITLE
Android/IDEs/C/C++: Cxxdroid & CppDroid

### ISSUE THREAD

**Issue by fititnt** [EticaAI/inclusao-digital#27]
Conforme testes prévios já realizados via comunidade AfricaBR, link <https://www.facebook.com/groups/africabr/learning_content/?filter=619941085190747&post=278083736444754>, podemos adicionar o `Cxxdroid` e o `CppDroid` como opções para compilar códigos C/C++.

**Comment by fititnt** [comment]
Obrigado @ThesllaDev !

**Comment by ThesllaDev** [comment]
> 
> 
> Obrigado @ThesllaDev !

Obrigado você pelo excelente apoio!

**Comment by Belu-momhn** [comment]
- 1 open play store
- 2 install cppdroid c/c++
- 3 errors update error their way out clear
- 4 join my discord server cppdroid

**Note:** install update error install cppdroid c/c++ the other

- [x] cppdroid install play store c/c++
